### ISSUE TITLE
GitPitch is unhelpful here

### ISSUE THREAD

**Issue by foobarbecue** [GothenburgBitFactory/taskserver-setup#4]
Most taskwarrior things have great installation and getting started instructions, but the for some reason the taskserver ones are in the form of a slideshow. Why? Nobody wants to read installation instructions in a form where section headers take up an entire browser window.

**Comment by ddeimeke** [comment]
@foobarbecue We already had that on a html page and people were not following the documentation. So we cut the website into digestable pieces and got a lot less questions.

**Comment by infinisil** [comment]
GitPitch is horrible tbh, you can't just scroll through to find what you need. Fortunately you can browse the document more comfortably here on GitHub: https://github.com/GothenburgBitFactory/taskserver-setup/blob/master/PITCHME.md

**Comment by alliejp-tv** [comment]
:-1: to using a slideshow for documentation. I (personally) found it jarring and difficult to follow - lots of huge text flashing across my monitor is very difficult to digest. 

I don't see what's particularly wrong with with [the markdown version](https://github.com/GothenburgBitFactory/taskserver-setup/blob/master/PITCHME.md)? It's fairly easy to parse and digest (minus all the reveal.js decoration required to make it a slideshow).

**Comment by pbeckingham** [comment]
We have gone through many variants of the Taskserver setup and troubleshooting documents. Here is what we have learned:

1. No matter what the form, some people read it, understand it, and use it to solve the problem. These are not the people we are trying to address.
2. When the document is in linear form, it's sheer length seems to be a barrier to some people, who simply don't want to read.  These people then come to us and we get the same questions, over and over, all of which are addressed in the documentation, if only it was actually read.
3. When the document was broken into several web pages, people don't read them all. Instead they think that Google magically knows which page contains the right solution (it doesn't folks, it's mostly dependent on your inputs, and if your inputs were perfect, you would probably not need to ask), and they end up reading one page. Then they ask us the same questions, over and over, all of which are addressed in the documentation, if only it was actually read.
4. When the document is in linear presentation form, the complaint is that it's not searchable, which is true. The point is that you need to read it all, in sequence. People skip through presentations until they see something they like, and read that.  Then they ask us the same questions, over and over, all of which are addressed in hte documentation, if only it was actually read.
5. When the documentation is in GitPitch format, it hides the length, and forces people to navigate. I think the result is that more of it gets read, but still there are complaints. Then they ask us the same questions, over and over,, all of which are addressed in the documentation, if only it was actually read.

The net result is that troubleshooting a secure server is complex, but people think it's easy, and there is only one solution to their one problem.  This is not usually the case, instead, the problem is that our documentation which states that setting up a secure server is tricky, and not for everyone, seems to deter no one, and they plough ahead making assumptions and skipping steps. Then ask us to solve it.

It's a difficult problem.  We've tried several options. There just doesn't seem to be a solution that fits everyone.

I'm tired of hearing about this. The issue is closed, and will stay closed unless someone steps up and actually helps, but that has not happened in the last 7 years. What we need is someone who thinks they have a solution to create the right document, and commits to supporting the users that don't read it.
